# Лабораторная работа №3

#### Упражнение 1

В данном упражнении необходимо смоделировать данные и построить на них парную линейную регрессионную модель. Для того, чтобы ваши результаты были воспроизводимыми, перед началом выполнения упражнения убедитесь, что вы используете функцию `set.seed()`.

(a) Используйте функцию `rnorm()` для того, чтобы создать вектор `x`, содержащий 100 наблюдаемых значений нормальной случайной величины `N(0, 1)` (математическое ожидание 0 и дисперсия 1). Эти данные будут соответсвовать независимой переменной `X`.

(b) Используйте функцию `rnorm()` для того, чтобы создать вектор `eps`, содержащий 100 наблюдаемых значений нормальной случайной величины `N(0, 0.25)`.

(c) Используйте `x` и `eps`, чтобы сгенерировать вектор `y` в соответствии с моделью `Y = -1 + 0.5X + EPS.` Какова длина вектора `y`? Каковы значения коэффициентов `beta0` и `beta1` в данной модели?

(d) Постройте точечную диаграмму, которая будет показывать связь `x` и `y`. Прокомментируйте ваши наблюдения.

(e) Используя метод наименьших квадратов постройте линейную регрессионную модель для описания `y` через `x`. Прокомментируйте полученную модель. Сравните оценки и реальные значения для коэффициентов `beta0` и `beta1` модели.

(f) Отобразите регрессионную линию, полученную методом наименьших квадратов,  на точечной диаграмме из пункта (d).  Постройте истинную линию регрессии используя другой цвет. Используйте функцию `legend()` для того, чтобы создать соответствующую легенду графика.

(g) Измените процесс генерации данных таким образом, чтобы уменьшить шум (noise) в данных. При фиксированной модели вы можете это сделать уменьшив дисперсию  нормальной случайной величины, с помощью которой моделируются ошибки. После этого повторите пункты (a)-(f). Опишите полученные результаты.

(h)  Измените процесс генерации данных таким образом, чтобы увеличить шум в данных. После этого повторите пункты (a)-(f). Опишите полученные результаты.

(i) Каковы доверительные интервалы для коэффициентов модели `beta0` и `beta1` построенной по исходным данным, данным с большим шумом, данным с меньшим шумом? Прокомментируйте ваши результаты.

#### Упражнение 2

Данное упражнение основано на множестве данных `Boston` из библиотеки `MASS`. Вы попытаетесь предсказать уровень преступности основываясь на других данных их этого множества. Другими словами, уровень преступности будет переменной отклика, а остальные переменные -- предикторами.

(a) Для каждого предиктора постройте парную линейную регрессионную модель для описания переменной отклика. Опишите ваши результаты. В каких моделях есть статистически значимая связь между предиктором и переменной отклика? Создайте несколько графиков, чтобы поддержать ваши выводы.

(b) Постройте множественную линейную регрессионную модель используя все предикторы. Опишите результаты. Для каких предикторов мы можем отвергнуть нулевую гипотезу `H_0: beta_j = 0 `?

(c) Сравните ваши результаты из пунктов (a) и (b). Постройте график, отображающий парные регрессионные коэффициенты из пункта (a) по оси `x`, а множественные регрессионные коэффициенты из пункта (b) по оси `y`. То есть, каждому предиктору будет соответствовать точка на графике. Его коэффициент из парной регрессии будет показан на оси `x`, а соответсвующий коэффициент из множественной регрессии -- на оси `y`.

(d) Есть ли признаки того, что между каким-либо предиктором и переменной отклика есть нелинейная связь? Для того, чтобы ответить на этот вопрос, для каждого предиктора `X` постройте модель вида `Y = beta0 + beta1 * X + beta2 * X^2 + beta3 * X^3 + EPS`.

