# Лабораторная работа №5

#### Упражнение 1

Данное упражнение основано на множестве данных `Weekly` из библиотеки `ISLR`. Оно содержит информацию о недельной доходности индекса S&P 500 за 21 год, с начала 1990 года до конца 2010 года.

(a) Получите описательные статистики для множества данных `Weekly`. Исследуйте данные графически. Есть ли в данных какие-либо связи?

(b) Используйте все множество данных, чтобы построить логистическую регрессию с переменной `Direction` в качестве переменной отклика и 5-ю `Lag` переменными, а также переменной `Volume` в качестве предикторов. Используйте функцию `summary()` чтобы вывести результаты. Являются ли какие-либо предикторы статистически значимыми? Если да, то какие?

(c) Постройте матрицу неточностей (confusion matrix) для модели из пункта (b). Какова точность данной модели? Исходя из матрицы неточностей поясните, какие типы ошибок делает логистическая регрессия в данном случае.

(d) Постройте логистическую регрессию, используя в качестве обучающего множества данные за период с 1990 года до 2008 года с единственным предиктором `Lag2`. Постройте матрицу неточностей и вычислите точность данной модели на тестовом множестве -- данных за 2009 и 2010 годы.

(e) Поэкспериментируйте с различными комбинациями предикторов, включая трансформацию предикоторов и добавление взаимодействий предикторов. Какой из методов дал наилучший результат?

#### Упражнение 2

В данном упражнении на данных `Auto` вам нужно будет построить модель, чтобы предсказывать будет ли у данной машины высокий или же низкий расход топлива.

(a) Постройте категориальную переменную `mpg01`, которая равна 1, если соответсвующее значение `mpg` выше медианного, и 0 -- в противном случае.

(b) Исследуйте данные графически, чтобы выявить связи между `mpg01` и другими переменными. Какие переменные могут быть полезны при предсказании `mpg01`?

(c) Разделите данные на обучающее и тестовое множества.

(d) Постройте логистическую регрессию на обучающем множестве, используя в качестве переменной отклика `mpg01`, а в качестве предикторов -- переменные, отобранные в пункте (b). Какова точность модели на тестовом множестве?







