#Лабораторная работа №6

#### Упражнение 1

Данное упражнение основано на множестве данных `Weekly` из библиотеки `ISLR`. Оно содержит информацию о недельной доходности индекса S&P 500 за 21 год, с начала 1990 года до конца 2010 года.

(a) Постройте LDA модель, используя в качестве обучающего множества данные за период с 1990 года до 2008 года с единственным предиктором `Lag2`. Постройте матрицу неточностей и вычислите точность данной модели на тестовом множестве -- данных за 2009 и 2010 годы.

(b) Повторите пункт (a) с QDA моделью.

(с) Сравниете результаты, полученные на этих данных с использованием логистической регрессии(см. л.р. №5), LDA и QDA.

#### Упражнение 2

В данном упражнении на данных `Auto` вам нужно будет построить модель, чтобы предсказывать будет ли у данной машины высокий или же низкий расход топлива.

(a) Постройте категориальную переменную `mpg01`, которая равна 1, если соответсвующее значение `mpg` выше медианного, и 0 -- в противном случае.

(b) Исследуйте данные графически, чтобы выявить связи между `mpg01` и другими переменными. Какие переменные могут быть полезны при предсказании `mpg01`?

(c) Разделите данные на обучающее и тестовое множества.

(d) Постройте LDA модель на обучающем множестве, используя в качестве переменной отклика `mpg01`, а в качестве предикторов -- переменные, отобранные в пункте (b). Какова точность модели на тестовом множестве?

(e) Повторите пункт (d) для QDA модели.